#!/bin/sh
if [ -x /opt/redislabs/bin/python2.7 ]; then
    python=/opt/redislabs/bin/python2.7
else
    python=/usr/bin/python2.7
fi

GRACE_TIME_MINS=1440
$python -O /opt/redislabs/lib/cnm/redis_cleanup.pyo $GRACE_TIME_MINS
$python -O /opt/redislabs/lib/cnm/backup_mgr.pyo --pid-file /var/run/backup_mgr.pid
